# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
cause_list = [
"Alzheimer's Association",
"American Cancer Society",
"American Diabetes Association",
"American Heart Association",
"American Jewish Joint Distribution Committee",
"American Kidney Fund",
"American National Red Cross",
"American SPCA",
"AmeriCares Foundation",
"Big Brothers Big Sisters of America",
"Boy Scouts of America",
"Boys & Girls Clubs of America",
"Brother's Brother Foundation",
"Campus Crusade for Christ International",
"CARE USA",
"Catholic Charities USA",
"Catholic Medical Mission Board",
"Catholic Relief Services",
"ChildFund International",
"Children International",
"Children's Hospital Boston",
"Christian Aid Ministries",
"Christian Appalachian Project",
"Christian Broadcasting Network",
"Chronic Disease Fund",
"Combined Jewish Philanthropies",
"Compassion International",
"Cystic Fibrosis Foundation",
"Dana-Farber Cancer Institute",
"Direct Relief International",
"Doctors Without Borders USA",
"Easter Seals",
"Father Flanagan's Boys' Home",
"Feed the Children",
"Feeding America",
"Food for the Poor",
"George W Bush Foundation",
"Good 360",
"Goodwill Industries International",
"Habitat for Humanity International",
"Heifer International",
"Houston Food Bank",
"Humane Society of the United States",
"International Rescue Committee",
"JDRF",
"Junior Achievement USA",
"Kingsway Charities",
"Leukemia & Lymphoma Society",
"Lutheran Services in America",
"Make-A-Wish Foundation of America",
"MAP International",
"March of Dimes Foundation",
"Marine Toys for Tots Foundation",
"Matthew 25: Ministries",
"Mayo Clinic",
"Medical Teams International",
"Memorial Sloan-Kettering Cancer Center",
"Metropolitan Museum of Art",
"Metropolitan Opera Association",
"Mount Sinai School of Medicine and Hospital",
"Muscular Dystrophy Association",
"National Cancer Coalition",
"National Multiple Sclerosis Society",
"Nature Conservancy",
"New York-Presbyterian Hospital",
"Operation Blessing International Relief & Dev.",
"Operation Compassion",
"Paralyzed Veterans of America",
"PATH",
"Planned Parenthood Federation of America",
"Population Services International",
"Project HOPE",
"Public Broadcasting Service",
"Robin Hood Foundation",
"Rotary Foundation of Rotary International",
"Salvation Army",
"Samaritan's Purse",
"Save the Children Federation",
"Scholarship America",
"Shriners Hospitals for Children",
"Smile Train",
"Smithsonian Institution",
"St. Jude Children's Research Hospital",
"St. Mary's Food Bank Alliance",
"Step Up for Students",
"Susan G. Komen for the Cure",
"Teach for America",
"The Arc",
"UJA/Federation of New York",
"United Negro College Fund",
"United Service Organizations",
"United States Fund for UNICEF",
"United Way",
"WGBH Educational Foundation",
"World Help",
"World Vision",
"World Wildlife Fund",
"Wycliffe Bible Translators",
"YMCA",
"Young Life",
]

puts 'Preparing to create seed Causes'

cause_list.each do |name|
  Cause.find_or_create_by_name(name)
end

puts 'All seed Causes found or created'
